Bump hyper to 0.14.3
gotham-rs/gotham pull request #530
Opened 2021-03-16 02:02 UTC by karim-agha

- reacting to: https://rustsec.org/advisories/RUSTSEC-2021-0020.html
- additional code cleanup to use `serde` instead of `serde_derive`.
- additional code cleanup to remove deprecated pre-rust2018 `extern crate`.
- updated some other crate versions.

2021-03-16 16:36 UTC, msrd0 requested changes
Thanks for applying some best practises! The CI has some failed tests, can you fix those please?

2021-03-16 16:36 UTC, msrd0 commented on examples/path/globs/Cargo.toml
> +serde = { version = "1.0", features = ["derive"] }
Please ensure all files end with a newline

2021-03-20 21:27 UTC, msrd0 commented
Hyper has been bumped in #524 already, but I'd still be interested in merging the other changes you made.

2021-03-21 00:02 UTC, karim-agha commented
I can't repro the clippy errors locally

2021-03-21 00:02 UTC, closed without merging